version: '3.7'

services:

  redis:
    image: redis
    ports:
      - 17381:6379

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - server_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 16433:5432
    networks:
      - default
      - serverdb

  server:
    build:
      context: ./app/server
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - '7005:7005'
    networks:
      - default
      - serverdb

  nginx-server:
    image: nginx:alpine
    volumes:
      - ./app/server/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=computer-service-service.dev.local
    networks:
      - default
      - outside
    depends_on:
      - server

  client:
    build:
      context: .
    depends_on:
      - redis
    volumes:
      - ./app/client:/app
    ports:
      - '7002:7002'
    networks:
      - default
      - serverdb

  nginx-client:
    image: nginx:alpine
    volumes:
      - ./app/client/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=computer-service-client.dev.local
    networks:
      - default
      - outside

volumes:
  server_db_data:

networks:
  serverdb:
    name: serverdb
    external: true
  outside:
    external: true
    name: nginx-proxy
